server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  activemq:
    broker-url: tcp://localhost:61616
  packages:
    trust-all: true